package enums;

public enum Commands {
    ADD,
    DELETE,
    UPDATE,
    READ_ALL,
    PROFIT,
    LIQUIDITY,
    REGISTER,
    isEXIST,
    isLoginEXIST,
    CAPITALS,
    CAPITALS_UPDATE, ADD_CURRENCY, RECORD, ADD_APIVES, UPDATE_APIVES, NEWCOMPANY, ERROR, UPDATE_COMPANY, TERMINATE
}
